export { default as addDocument } from "./add-document";
export { default as getCollectionRef } from "./get-collection-ref";
export { default as getCollectionSize } from "./get-collection-size";
export { default as getDocumentRef } from "./get-document-ref";
export { default as getDocument } from "./get-document";
export { default as setDocument } from "./set-document";
export { default as updateDocument } from "./update-document";
export { default as getAllData } from "./get-all-data";
export { default as getPagination } from "./get-pagination";
export { default as getCollection } from "./get-collection";
export type * from "./firestore.protocol";
